### ISSUE TITLE
button requires two clicks to open the slide menu

### ISSUE THREAD

**Issue by ghost** [JoanClaret/slide-and-swipe-menu#1]
Hello i have an issue i have set up slide-and-swipe on my site and the menu works correctly however it takes two clicks on the button i setup for the nav bar to actually open and after that it closes and opens with just one click but reloads the page and its back to two clicks to open it and it can be quite annoying

Please can you help me out

Kind Regards
Hayden

**Comment by JoanClaret** [comment]
Make sure you does not have class "ssm-nav-visible" in the HTML of the sliding navigation.

**Comment by ghost** [comment]
Thank you very much This worked

Kind Regards
Hayden

**Comment by JoanClaret** [comment]
Glad to help you
