### ISSUE TITLE
Open menu by swipe

### ISSUE THREAD

**Issue by daksamedia** [JoanClaret/slide-and-swipe-menu#16]
Hi @JoanClaret,

It's great works. Good job!
But suddenly, I got a sticky question
on my head.

How could I make slide swipe menu by swipe the screen?
Is it possible for you to make it on the next version?

Thank you anyway

**Comment by JoanClaret** [comment]
Hi, thanks!
sorry, at this moment this feature is not available.
it would be a great feature, but i'm currently too busy to allocate time on it.
feel free to PR if you can!
