### ISSUE TITLE
Unable to link within page for one page apps.

### ISSUE THREAD

**Issue by sapp006** [JoanClaret/slide-and-swipe-menu#17]
I have found your code to be very helpful and useful. Thanks! My only issue is that I was unable to jump to different sections of my app with your menu so I removed the  e.preventDefault() function from the ssm-toggle-nav function. 

I do not see any difference after removing it, except that I can now use my internal links.  

Will this cause any problems that I might not be aware of?

**Comment by JoanClaret** [comment]
Hi there, sorry for this delay. i've been really busy.
i don't really get why you are unable to jump to different sections of your app. looks like an implementation error.

anyways, if you remove this preventDefault, the only problem you'll have, is that if the clicked element is a link, the page will scroll to the top (in case it's not there).

hope this is helpful for you.

cheers
Joan
