### ISSUE TITLE
Menu is open on loading site on Androide standard browser.

### ISSUE THREAD

**Issue by Sandbakk** [JoanClaret/slide-and-swipe-menu#2]
The menu is already open on loading site in the standard browser on Android 5. This is both on the plugin page and the demo page. It works perfect in other browsers on the same device.

**Comment by JoanClaret** [comment]
Hi
does it move by swipe?

**Comment by sholoma** [comment]
Yes, it moves. I confirm, it is opened in default android browser (tested android 5 and 4.4)

**Comment by JoanClaret** [comment]
@Sandbakk @sholoma did you try to add vendor prefixes to nav's default state?
this should fix it.

https://github.com/JoanClaret/slide-and-swipe-menu/blob/master/demo/css/slide-and-swipe-menu.css#L14

```
nav {
  -webkit-transform: translate(-280px,0);
  -moz-transform:    translate(-280px,0);
  -ms-transform:     translate(-280px,0);
  -o-transform:      translate(-280px,0);
  transform:         translate(-280px,0);
}
```
