### ISSUE TITLE
swipe from the right

### ISSUE THREAD

**Issue by lubomirblazekcz** [JoanClaret/slide-and-swipe-menu#3]
Hello, is there an easy way how to define the slide from the right side of the screen?
Or if you could help me with what should I change in the script.

Thanks!

**Comment by JoanClaret** [comment]
No, sorry, at this moment there is not an easy way to do it. 
If we want to add this feature, we should implement it.

**Comment by tranthaihoang** [comment]
Not on the right is a big mistake

**Comment by Darex1991** [comment]
https://github.com/IIIu6ko/right-side-slide-and-swipe-menu
