### ISSUE TITLE
Problem with re-calc when resize or orientation change

### ISSUE THREAD

**Issue by ghost** [JoanClaret/slide-and-swipe-menu#4]
Hi, Thanks for great and simply script. I have issue - when i set different sizes of the menu with media queries, the script does not change transform to new values from css. Can you take a look?

**Comment by JoanClaret** [comment]
Hi! 
Thanks for your comment.
What about to reinitialize on window resize?

``` javascript
$( window ).resize(function() {
  $('.nav').slideAndSwipe();
});
```
