### ISSUE TITLE
Duplicate element when have two different kind of menu and events js

### ISSUE THREAD

**Issue by waltercassiano** [JoanClaret/slide-and-swipe-menu#7]
I've made a fork and done some updates. 
- Nav clone element 
- JS Event - Open / Close menu by js event
- Option to use '%' instead of 'px' to nav postion.  When using a fluid width on nav cause a strange behavior on browser or mobile resize/orientationchange. 

If interesting can I do a pull request ?

**Comment by JoanClaret** [comment]
sure!

**Comment by JoanClaret** [comment]
The only point i don't understand is why somebody needs to clone the navigation. can you explain it?

**Comment by waltercassiano** [comment]
So, in my case,  the same nav I can have two different kind of layout. 
If I have one nav and different kind of layout I would not like that JS affect another one with different layout...  Like a horizontal nav...

**Comment by JoanClaret** [comment]
i can't figure out what do you mean. 
maybe can you post a simplified codepen example?

**Comment by dsoldera** [comment]
Hi @JoanClaret 

I´ve working with @waltercassiano. This fork that he worked is when the website has the same Menu for Desktop and Mobile Version. Even using this Plugin only for Mobile Breakpoint, once the Swipe occured, its changes the DOM. And on resize, the Only Menu is broken on Desktop Version. 

Clonning the Menu, will avoid the Broken Menu after the DOM is changed, on resize.

Regards.

**Comment by JoanClaret** [comment]
ok, thanks!
let's try it then. 
go ahead with the PR!
